/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AgentMandateInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizeSpend"
      | "createMandate"
      | "freezeMandate"
      | "isProviderAllowed"
      | "isServiceAllowed"
      | "mandates"
      | "owner"
      | "refundSpend"
      | "renounceOwnership"
      | "transferOwnership"
      | "unfreezeMandate"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MandateCreated"
      | "MandateFrozen"
      | "MandateUnfrozen"
      | "MandateUpdated"
      | "OwnershipTransferred"
      | "SpendAuthorized"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizeSpend",
    values: [AddressLike, AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createMandate",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string[],
      AddressLike[],
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "freezeMandate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isProviderAllowed",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isServiceAllowed",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "mandates",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "refundSpend",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unfreezeMandate",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizeSpend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMandate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "freezeMandate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isProviderAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isServiceAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mandates", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "refundSpend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unfreezeMandate",
    data: BytesLike
  ): Result;
}

export namespace MandateCreatedEvent {
  export type InputTuple = [
    agent: AddressLike,
    totalBudget: BigNumberish,
    dailyLimit: BigNumberish,
    perTransactionLimit: BigNumberish
  ];
  export type OutputTuple = [
    agent: string,
    totalBudget: bigint,
    dailyLimit: bigint,
    perTransactionLimit: bigint
  ];
  export interface OutputObject {
    agent: string;
    totalBudget: bigint;
    dailyLimit: bigint;
    perTransactionLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MandateFrozenEvent {
  export type InputTuple = [agent: AddressLike];
  export type OutputTuple = [agent: string];
  export interface OutputObject {
    agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MandateUnfrozenEvent {
  export type InputTuple = [agent: AddressLike];
  export type OutputTuple = [agent: string];
  export interface OutputObject {
    agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MandateUpdatedEvent {
  export type InputTuple = [agent: AddressLike];
  export type OutputTuple = [agent: string];
  export interface OutputObject {
    agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SpendAuthorizedEvent {
  export type InputTuple = [agent: AddressLike, amount: BigNumberish];
  export type OutputTuple = [agent: string, amount: bigint];
  export interface OutputObject {
    agent: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentMandate extends BaseContract {
  connect(runner?: ContractRunner | null): AgentMandate;
  waitForDeployment(): Promise<this>;

  interface: AgentMandateInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizeSpend: TypedContractMethod<
    [
      _agent: AddressLike,
      _provider: AddressLike,
      _serviceType: string,
      _amount: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;

  createMandate: TypedContractMethod<
    [
      _agent: AddressLike,
      _totalBudget: BigNumberish,
      _dailyLimit: BigNumberish,
      _perTransactionLimit: BigNumberish,
      _expiresAt: BigNumberish,
      _allowedServices: string[],
      _allowedProviders: AddressLike[],
      _restrictProviders: boolean
    ],
    [void],
    "nonpayable"
  >;

  freezeMandate: TypedContractMethod<
    [_agent: AddressLike],
    [void],
    "nonpayable"
  >;

  isProviderAllowed: TypedContractMethod<
    [_agent: AddressLike, _provider: AddressLike],
    [boolean],
    "view"
  >;

  isServiceAllowed: TypedContractMethod<
    [_agent: AddressLike, _serviceType: string],
    [boolean],
    "view"
  >;

  mandates: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint
      ] & {
        totalBudget: bigint;
        dailyLimit: bigint;
        perTransactionLimit: bigint;
        expiresAt: bigint;
        isActive: boolean;
        restrictProviders: boolean;
        spentToday: bigint;
        lastSpentDay: bigint;
        totalSpent: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  refundSpend: TypedContractMethod<
    [_agent: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unfreezeMandate: TypedContractMethod<
    [_agent: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizeSpend"
  ): TypedContractMethod<
    [
      _agent: AddressLike,
      _provider: AddressLike,
      _serviceType: string,
      _amount: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createMandate"
  ): TypedContractMethod<
    [
      _agent: AddressLike,
      _totalBudget: BigNumberish,
      _dailyLimit: BigNumberish,
      _perTransactionLimit: BigNumberish,
      _expiresAt: BigNumberish,
      _allowedServices: string[],
      _allowedProviders: AddressLike[],
      _restrictProviders: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "freezeMandate"
  ): TypedContractMethod<[_agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isProviderAllowed"
  ): TypedContractMethod<
    [_agent: AddressLike, _provider: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isServiceAllowed"
  ): TypedContractMethod<
    [_agent: AddressLike, _serviceType: string],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "mandates"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint,
        bigint
      ] & {
        totalBudget: bigint;
        dailyLimit: bigint;
        perTransactionLimit: bigint;
        expiresAt: bigint;
        isActive: boolean;
        restrictProviders: boolean;
        spentToday: bigint;
        lastSpentDay: bigint;
        totalSpent: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "refundSpend"
  ): TypedContractMethod<
    [_agent: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unfreezeMandate"
  ): TypedContractMethod<[_agent: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "MandateCreated"
  ): TypedContractEvent<
    MandateCreatedEvent.InputTuple,
    MandateCreatedEvent.OutputTuple,
    MandateCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MandateFrozen"
  ): TypedContractEvent<
    MandateFrozenEvent.InputTuple,
    MandateFrozenEvent.OutputTuple,
    MandateFrozenEvent.OutputObject
  >;
  getEvent(
    key: "MandateUnfrozen"
  ): TypedContractEvent<
    MandateUnfrozenEvent.InputTuple,
    MandateUnfrozenEvent.OutputTuple,
    MandateUnfrozenEvent.OutputObject
  >;
  getEvent(
    key: "MandateUpdated"
  ): TypedContractEvent<
    MandateUpdatedEvent.InputTuple,
    MandateUpdatedEvent.OutputTuple,
    MandateUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SpendAuthorized"
  ): TypedContractEvent<
    SpendAuthorizedEvent.InputTuple,
    SpendAuthorizedEvent.OutputTuple,
    SpendAuthorizedEvent.OutputObject
  >;

  filters: {
    "MandateCreated(address,uint256,uint256,uint256)": TypedContractEvent<
      MandateCreatedEvent.InputTuple,
      MandateCreatedEvent.OutputTuple,
      MandateCreatedEvent.OutputObject
    >;
    MandateCreated: TypedContractEvent<
      MandateCreatedEvent.InputTuple,
      MandateCreatedEvent.OutputTuple,
      MandateCreatedEvent.OutputObject
    >;

    "MandateFrozen(address)": TypedContractEvent<
      MandateFrozenEvent.InputTuple,
      MandateFrozenEvent.OutputTuple,
      MandateFrozenEvent.OutputObject
    >;
    MandateFrozen: TypedContractEvent<
      MandateFrozenEvent.InputTuple,
      MandateFrozenEvent.OutputTuple,
      MandateFrozenEvent.OutputObject
    >;

    "MandateUnfrozen(address)": TypedContractEvent<
      MandateUnfrozenEvent.InputTuple,
      MandateUnfrozenEvent.OutputTuple,
      MandateUnfrozenEvent.OutputObject
    >;
    MandateUnfrozen: TypedContractEvent<
      MandateUnfrozenEvent.InputTuple,
      MandateUnfrozenEvent.OutputTuple,
      MandateUnfrozenEvent.OutputObject
    >;

    "MandateUpdated(address)": TypedContractEvent<
      MandateUpdatedEvent.InputTuple,
      MandateUpdatedEvent.OutputTuple,
      MandateUpdatedEvent.OutputObject
    >;
    MandateUpdated: TypedContractEvent<
      MandateUpdatedEvent.InputTuple,
      MandateUpdatedEvent.OutputTuple,
      MandateUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SpendAuthorized(address,uint256)": TypedContractEvent<
      SpendAuthorizedEvent.InputTuple,
      SpendAuthorizedEvent.OutputTuple,
      SpendAuthorizedEvent.OutputObject
    >;
    SpendAuthorized: TypedContractEvent<
      SpendAuthorizedEvent.InputTuple,
      SpendAuthorizedEvent.OutputTuple,
      SpendAuthorizedEvent.OutputObject
    >;
  };
}
