/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface OutcomeRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "outcomes"
      | "owner"
      | "recordOutcome"
      | "renounceOwnership"
      | "transferOwnership"
      | "updateOutcomeState"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OutcomeRecorded"
      | "OutcomeStateChanged"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(functionFragment: "outcomes", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordOutcome",
    values: [string, string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateOutcomeState",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "outcomes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordOutcome",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateOutcomeState",
    data: BytesLike
  ): Result;
}

export namespace OutcomeRecordedEvent {
  export type InputTuple = [
    taskId: string,
    resultHash: string,
    deliveryHash: string,
    state: BigNumberish
  ];
  export type OutputTuple = [
    taskId: string,
    resultHash: string,
    deliveryHash: string,
    state: bigint
  ];
  export interface OutputObject {
    taskId: string;
    resultHash: string;
    deliveryHash: string;
    state: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OutcomeStateChangedEvent {
  export type InputTuple = [taskId: string, newState: BigNumberish];
  export type OutputTuple = [taskId: string, newState: bigint];
  export interface OutputObject {
    taskId: string;
    newState: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OutcomeRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): OutcomeRegistry;
  waitForDeployment(): Promise<this>;

  interface: OutcomeRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  outcomes: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, string, bigint, bigint] & {
        taskId: string;
        requestHash: string;
        resultHash: string;
        deliveryHash: string;
        state: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  recordOutcome: TypedContractMethod<
    [
      _taskId: string,
      _requestHash: string,
      _resultHash: string,
      _deliveryHash: string,
      _initialState: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateOutcomeState: TypedContractMethod<
    [_taskId: string, _newState: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "outcomes"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, string, bigint, bigint] & {
        taskId: string;
        requestHash: string;
        resultHash: string;
        deliveryHash: string;
        state: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordOutcome"
  ): TypedContractMethod<
    [
      _taskId: string,
      _requestHash: string,
      _resultHash: string,
      _deliveryHash: string,
      _initialState: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateOutcomeState"
  ): TypedContractMethod<
    [_taskId: string, _newState: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "OutcomeRecorded"
  ): TypedContractEvent<
    OutcomeRecordedEvent.InputTuple,
    OutcomeRecordedEvent.OutputTuple,
    OutcomeRecordedEvent.OutputObject
  >;
  getEvent(
    key: "OutcomeStateChanged"
  ): TypedContractEvent<
    OutcomeStateChangedEvent.InputTuple,
    OutcomeStateChangedEvent.OutputTuple,
    OutcomeStateChangedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "OutcomeRecorded(string,string,string,uint8)": TypedContractEvent<
      OutcomeRecordedEvent.InputTuple,
      OutcomeRecordedEvent.OutputTuple,
      OutcomeRecordedEvent.OutputObject
    >;
    OutcomeRecorded: TypedContractEvent<
      OutcomeRecordedEvent.InputTuple,
      OutcomeRecordedEvent.OutputTuple,
      OutcomeRecordedEvent.OutputObject
    >;

    "OutcomeStateChanged(string,uint8)": TypedContractEvent<
      OutcomeStateChangedEvent.InputTuple,
      OutcomeStateChangedEvent.OutputTuple,
      OutcomeStateChangedEvent.OutputObject
    >;
    OutcomeStateChanged: TypedContractEvent<
      OutcomeStateChangedEvent.InputTuple,
      OutcomeStateChangedEvent.OutputTuple,
      OutcomeStateChangedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
