/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ProviderRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addService"
      | "owner"
      | "providers"
      | "registerProvider"
      | "removeService"
      | "renounceOwnership"
      | "supportedServices"
      | "transferOwnership"
      | "updateProviderStatus"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "ProviderRegistered"
      | "ProviderStatusUpdated"
      | "ServiceAdded"
      | "ServiceRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addService",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "providers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerProvider",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeService",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportedServices",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProviderStatus",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addService", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "providers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeService",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedServices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProviderStatus",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProviderRegisteredEvent {
  export type InputTuple = [providerAddress: AddressLike, name: string];
  export type OutputTuple = [providerAddress: string, name: string];
  export interface OutputObject {
    providerAddress: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProviderStatusUpdatedEvent {
  export type InputTuple = [providerAddress: AddressLike, status: BigNumberish];
  export type OutputTuple = [providerAddress: string, status: bigint];
  export interface OutputObject {
    providerAddress: string;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ServiceAddedEvent {
  export type InputTuple = [providerAddress: AddressLike, serviceType: string];
  export type OutputTuple = [providerAddress: string, serviceType: string];
  export interface OutputObject {
    providerAddress: string;
    serviceType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ServiceRemovedEvent {
  export type InputTuple = [providerAddress: AddressLike, serviceType: string];
  export type OutputTuple = [providerAddress: string, serviceType: string];
  export interface OutputObject {
    providerAddress: string;
    serviceType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProviderRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ProviderRegistry;
  waitForDeployment(): Promise<this>;

  interface: ProviderRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addService: TypedContractMethod<
    [_providerAddress: AddressLike, _serviceType: string],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  providers: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, bigint] & {
        providerAddress: string;
        name: string;
        status: bigint;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  registerProvider: TypedContractMethod<
    [_providerAddress: AddressLike, _name: string],
    [void],
    "nonpayable"
  >;

  removeService: TypedContractMethod<
    [_providerAddress: AddressLike, _serviceType: string],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  supportedServices: TypedContractMethod<
    [arg0: AddressLike, arg1: string],
    [boolean],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateProviderStatus: TypedContractMethod<
    [_providerAddress: AddressLike, _status: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addService"
  ): TypedContractMethod<
    [_providerAddress: AddressLike, _serviceType: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "providers"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, bigint] & {
        providerAddress: string;
        name: string;
        status: bigint;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerProvider"
  ): TypedContractMethod<
    [_providerAddress: AddressLike, _name: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeService"
  ): TypedContractMethod<
    [_providerAddress: AddressLike, _serviceType: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportedServices"
  ): TypedContractMethod<[arg0: AddressLike, arg1: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateProviderStatus"
  ): TypedContractMethod<
    [_providerAddress: AddressLike, _status: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProviderRegistered"
  ): TypedContractEvent<
    ProviderRegisteredEvent.InputTuple,
    ProviderRegisteredEvent.OutputTuple,
    ProviderRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ProviderStatusUpdated"
  ): TypedContractEvent<
    ProviderStatusUpdatedEvent.InputTuple,
    ProviderStatusUpdatedEvent.OutputTuple,
    ProviderStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ServiceAdded"
  ): TypedContractEvent<
    ServiceAddedEvent.InputTuple,
    ServiceAddedEvent.OutputTuple,
    ServiceAddedEvent.OutputObject
  >;
  getEvent(
    key: "ServiceRemoved"
  ): TypedContractEvent<
    ServiceRemovedEvent.InputTuple,
    ServiceRemovedEvent.OutputTuple,
    ServiceRemovedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProviderRegistered(address,string)": TypedContractEvent<
      ProviderRegisteredEvent.InputTuple,
      ProviderRegisteredEvent.OutputTuple,
      ProviderRegisteredEvent.OutputObject
    >;
    ProviderRegistered: TypedContractEvent<
      ProviderRegisteredEvent.InputTuple,
      ProviderRegisteredEvent.OutputTuple,
      ProviderRegisteredEvent.OutputObject
    >;

    "ProviderStatusUpdated(address,uint8)": TypedContractEvent<
      ProviderStatusUpdatedEvent.InputTuple,
      ProviderStatusUpdatedEvent.OutputTuple,
      ProviderStatusUpdatedEvent.OutputObject
    >;
    ProviderStatusUpdated: TypedContractEvent<
      ProviderStatusUpdatedEvent.InputTuple,
      ProviderStatusUpdatedEvent.OutputTuple,
      ProviderStatusUpdatedEvent.OutputObject
    >;

    "ServiceAdded(address,string)": TypedContractEvent<
      ServiceAddedEvent.InputTuple,
      ServiceAddedEvent.OutputTuple,
      ServiceAddedEvent.OutputObject
    >;
    ServiceAdded: TypedContractEvent<
      ServiceAddedEvent.InputTuple,
      ServiceAddedEvent.OutputTuple,
      ServiceAddedEvent.OutputObject
    >;

    "ServiceRemoved(address,string)": TypedContractEvent<
      ServiceRemovedEvent.InputTuple,
      ServiceRemovedEvent.OutputTuple,
      ServiceRemovedEvent.OutputObject
    >;
    ServiceRemoved: TypedContractEvent<
      ServiceRemovedEvent.InputTuple,
      ServiceRemovedEvent.OutputTuple,
      ServiceRemovedEvent.OutputObject
    >;
  };
}
