/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAgentMandate,
  IAgentMandateInterface,
} from "../../../contracts/PaymentEscrow.sol/IAgentMandate";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "agent",
        type: "address",
      },
      {
        internalType: "address",
        name: "provider",
        type: "address",
      },
      {
        internalType: "string",
        name: "serviceType",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "authorizeSpend",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "agent",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "refundSpend",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAgentMandate__factory {
  static readonly abi = _abi;
  static createInterface(): IAgentMandateInterface {
    return new Interface(_abi) as IAgentMandateInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAgentMandate {
    return new Contract(address, _abi, runner) as unknown as IAgentMandate;
  }
}
