/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface PaymentEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "escrowPayment"
      | "intents"
      | "mandateContract"
      | "owner"
      | "refundPayment"
      | "renounceOwnership"
      | "settlePayment"
      | "settledTasks"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PaymentEscrowed"
      | "PaymentRefunded"
      | "PaymentSettled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "escrowPayment",
    values: [string, AddressLike, AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "intents", values: [string]): string;
  encodeFunctionData(
    functionFragment: "mandateContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "refundPayment",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "settlePayment",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "settledTasks",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "escrowPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "intents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mandateContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "refundPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settlePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settledTasks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentEscrowedEvent {
  export type InputTuple = [
    paymentId: string,
    agent: AddressLike,
    provider: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    paymentId: string,
    agent: string,
    provider: string,
    amount: bigint
  ];
  export interface OutputObject {
    paymentId: string;
    agent: string;
    provider: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentRefundedEvent {
  export type InputTuple = [
    paymentId: string,
    agent: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [paymentId: string, agent: string, amount: bigint];
  export interface OutputObject {
    paymentId: string;
    agent: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentSettledEvent {
  export type InputTuple = [
    paymentId: string,
    taskId: string,
    provider: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    paymentId: string,
    taskId: string,
    provider: string,
    amount: bigint
  ];
  export interface OutputObject {
    paymentId: string;
    taskId: string;
    provider: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PaymentEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): PaymentEscrow;
  waitForDeployment(): Promise<this>;

  interface: PaymentEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  escrowPayment: TypedContractMethod<
    [
      _paymentId: string,
      _agent: AddressLike,
      _provider: AddressLike,
      _serviceType: string,
      _amount: BigNumberish
    ],
    [void],
    "payable"
  >;

  intents: TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, string, boolean, boolean, boolean] & {
        agent: string;
        provider: string;
        amount: bigint;
        serviceType: string;
        isEscrowed: boolean;
        isSettled: boolean;
        isRefunded: boolean;
      }
    ],
    "view"
  >;

  mandateContract: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  refundPayment: TypedContractMethod<
    [_paymentId: string],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  settlePayment: TypedContractMethod<
    [_paymentId: string, _taskId: string],
    [void],
    "nonpayable"
  >;

  settledTasks: TypedContractMethod<[arg0: string], [boolean], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "escrowPayment"
  ): TypedContractMethod<
    [
      _paymentId: string,
      _agent: AddressLike,
      _provider: AddressLike,
      _serviceType: string,
      _amount: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "intents"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, string, boolean, boolean, boolean] & {
        agent: string;
        provider: string;
        amount: bigint;
        serviceType: string;
        isEscrowed: boolean;
        isSettled: boolean;
        isRefunded: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "mandateContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "refundPayment"
  ): TypedContractMethod<[_paymentId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settlePayment"
  ): TypedContractMethod<
    [_paymentId: string, _taskId: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settledTasks"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaymentEscrowed"
  ): TypedContractEvent<
    PaymentEscrowedEvent.InputTuple,
    PaymentEscrowedEvent.OutputTuple,
    PaymentEscrowedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentRefunded"
  ): TypedContractEvent<
    PaymentRefundedEvent.InputTuple,
    PaymentRefundedEvent.OutputTuple,
    PaymentRefundedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentSettled"
  ): TypedContractEvent<
    PaymentSettledEvent.InputTuple,
    PaymentSettledEvent.OutputTuple,
    PaymentSettledEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaymentEscrowed(string,address,address,uint256)": TypedContractEvent<
      PaymentEscrowedEvent.InputTuple,
      PaymentEscrowedEvent.OutputTuple,
      PaymentEscrowedEvent.OutputObject
    >;
    PaymentEscrowed: TypedContractEvent<
      PaymentEscrowedEvent.InputTuple,
      PaymentEscrowedEvent.OutputTuple,
      PaymentEscrowedEvent.OutputObject
    >;

    "PaymentRefunded(string,address,uint256)": TypedContractEvent<
      PaymentRefundedEvent.InputTuple,
      PaymentRefundedEvent.OutputTuple,
      PaymentRefundedEvent.OutputObject
    >;
    PaymentRefunded: TypedContractEvent<
      PaymentRefundedEvent.InputTuple,
      PaymentRefundedEvent.OutputTuple,
      PaymentRefundedEvent.OutputObject
    >;

    "PaymentSettled(string,string,address,uint256)": TypedContractEvent<
      PaymentSettledEvent.InputTuple,
      PaymentSettledEvent.OutputTuple,
      PaymentSettledEvent.OutputObject
    >;
    PaymentSettled: TypedContractEvent<
      PaymentSettledEvent.InputTuple,
      PaymentSettledEvent.OutputTuple,
      PaymentSettledEvent.OutputObject
    >;
  };
}
